version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub

sphinx.fail_on_warning: true

python:
  version: 3.7
  install:
    - requirements: docs/source/requirements.txt
    - method: pip
      path: .
